"""User model extended

Revision ID: 65539b2a449b
Revises: 4fe680449abb
Create Date: 2019-05-19 12:40:37.559175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65539b2a449b'
down_revision = '4fe680449abb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
